Cupcake-Project/Models/ErrorViewModel.cs
namespace Cupcake_Project.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Cupcake-Project/Models/Ingredient.cs
using Org.BouncyCastle.Asn1.Mozilla;
using System;

namespace Cupcake_Project.Models
{

	public class Ingredient
	{
		public Ingredient()
		{
		}

		public int ID { get; set; }
		public string Name { get; set; }
		public string Description { get; set; }
		public string Unit_of_Measurement { get; set; }
		public int Quantity_in_stock { get; set; }
	}

}

Cupcake-Project/Models/Product.cs
using System;

namespace Cupcake_Project.Models
{
	public class Product
	{
		public Product()
		{
		}


		public int ID { get; set; }
		public string Name { get; set; }
		public string Description { get; set; }
		public double Price { get; set; }
		public int Quantity_In_Stock { get; set; }
	}
}

Cupcake-Project/Models/Recipe.cs
using System;


namespace Cupcake_Project.Models
{
	public class Recipe
	{
		public Recipe()
		{
		}

		public int ID { get; set; }
		public int Product_ID { get; set; }
		public int Ingredient_ID { get; set; }
		public double Quantity_Required { get; set; }
	}
}

Cupcake-Project/Controllers/HomeController.cs
using Cupcake_Project.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Cupcake_Project.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Cupcake-Project/Controllers/IngredientController.cs
using Cupcake_Project;
using Cupcake_Project.Models;
using Microsoft.AspNetCore.Mvc;

namespace Cupcake_Project.Controllers
{
    public class IngredientController : Controller
    {
        private readonly IIngredientRepo repo;

        public IngredientController(IIngredientRepo repo)
        {
            this.repo = repo;
        }

        public IActionResult Index()
        {
            var ingredients = repo.GetAllIngredients();
            return View(ingredients);
        }

        public IActionResult ViewIngredient(int id)
        {
            var ingredient = repo.GetIngredient(id);
            return View(ingredient);
        }

        public IActionResult UpdateIngredient(int id)
        {
            Ingredient ingredient = repo.GetIngredient(id);
            if (ingredient == null)
            {
                return View("IngredientNotFound");
            }
            return View(ingredient);
        }

        public IActionResult UpdateIngredientToDatabase(Ingredient ingredient)
        {
            repo.UpdateIngredient(ingredient);

            return RedirectToAction("ViewIngredient", new { id = ingredient.ID });
        }

        public IActionResult InsertIngredient()
        {
            var ingredient = new Ingredient();
            return View(ingredient);
        }

        public IActionResult InsertIngredientToDatabase(Ingredient ingredient)
        {
            repo.InsertIngredient(ingredient);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteIngredient(Ingredient ingredient)
        {
            repo.DeleteIngredient(ingredient);
            return RedirectToAction("Index");
        }
    }
}

Cupcake-Project/Controllers/ProductController.cs
using Cupcake_Project;
using Cupcake_Project.Models;
using Microsoft.AspNetCore.Mvc;

namespace Cupcake_Project.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductRepo repo;

        public ProductController(IProductRepo repo)
        {
            this.repo = repo;
        }


        public IActionResult Index()
        {
            var products = repo.GetAllProducts();
            return View(products);
        }

        public IActionResult ViewProduct(int id)
        {
            var product = repo.GetProduct(id);
            return View(product);
        }

        public IActionResult UpdateProduct(int id)
        {
            var product = repo.GetProduct(id);

            if (product == null)
            {
                return View("ProductNotFound");
            }

            return View(product);
        }
        
        public IActionResult UpdateProductToDatabase(Product product)
        {
            repo.UpdateProduct(product);
            return RedirectToAction("ViewProduct", new { id = product.ID });
        }

        public IActionResult InsertProduct()
        {
            var product = new Product();
            return View(product);
        }

        public IActionResult InsertProductToDatabase(Product product)
        {
            repo.InsertProduct(product);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteProduct(Product product)
        {
            repo.DeleteProduct(product);
            return RedirectToAction("Index");
          
        }
       
    }
    
}

Cupcake-Project/Controllers/RecipeController.cs
using Cupcake_Project;
using Cupcake_Project.Models;
using Microsoft.AspNetCore.Mvc;

namespace Cupcake_Project.Controllers
{
    public class RecipeController : Controller
    {
        private readonly IRecipeRepo repo;

        public RecipeController(IRecipeRepo repo)
        {
            this.repo = repo;
        }


        public IActionResult Index()
        {
            var recipe = repo.GetAllRecipes();
            return View(recipe);
        }
        public IActionResult ViewRecipe(int id)
        {
            var recipe = repo.GetRecipe(id);
            return View(recipe);
        }
        public IActionResult UpdateRecipe(int id)
        {
            Recipe recipe = repo.GetRecipe(id);
            if (recipe == null)
            {
                return View("RecipeNotFound");
            }
            return View(recipe);
        }
        public IActionResult UpdateRecipeToDatabase(Recipe recipe)
        {
            repo.UpdateRecipe(recipe);
            return RedirectToAction("ViewRecipe", new { id = recipe.ID });
        }
        public IActionResult InsertRecipe()
        {
            var recipe = new Recipe();
            return View(recipe);
        }
        public IActionResult InsertRecipeToDatabase(Recipe recipe)
        {
            repo.InsertRecipe(recipe);
            return RedirectToAction("Index");
        }
        public IActionResult DeleteRecipe(Recipe recipe)
        {
            repo.DeleteRecipe(recipe);
            return RedirectToAction("Index");
        }
    }
}

Cupcake-Project/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Cupcake-Project/Views/Ingredient/Index.cshtml
@model IEnumerable<Ingredient>

<h2>Ingredients</h2>

<div style="display: block">
    <a href="/Ingredient/InsertIngredient/">Create a New Ingredient</a>
</div>

<table class="table">
    <tr>
        <th>Name</th>
        <th>Quantity In Stock</th>
        <th>Unit of Measurement</th>
    </tr>

    @foreach (var ingredient in @Model)
    {
        <tr>
            <td><a href=/Ingredient/ViewIngredient/@ingredient.ID>@ingredient.Name</a></td>
            <td>@ingredient.Quantity_in_stock</td>
            <td>@ingredient.Unit_of_Measurement</td>
        </tr>
    }

</table>

Cupcake-Project/Views/Ingredient/InsertIngredient.cshtml
@model Ingredient

<h2 class="text-center">Create a New Ingredient</h2>

@using (Html.BeginForm("InsertIngredientToDatabase", "Ingredient", "Post"))
{
    <input asp-for="ID" type="hidden" value="" />

    <label asp-for="Name" class="control-label">Name</label>
    <input type="text" name="Name" class="form-control" value="" />

    <label asp-for="Description" class="control-label">Description</label>
    <input type="text" name="Description" class="form-control" value="" />

    <label asp-for="Unit_of_Measurement" class="control-label">Unit of Measurement</label>
    <input type="number" name="Unit_of_Measruement" class="form-control" />

    <label asp-for="Quantity_in_stock" class="control-label">Quantity In Stock</label>
    <input type="number" name="Quantity_in_stock" class="form-control" />


    <button class="button" role="button" type="submit">Add Ingredient</button>
    <a class="button" href="/Ingredient/Index">Back</a>
}

Cupcake-Project/Views/Ingredient/UpdateIngredient.cshtml
@model Ingredient

<h2>Update @Model.Name</h2>

@using (Html.BeginForm("UpdateIngredientToDatabase", "Ingredient", "Post"))
{
    <input asp-for="ID" type="hidden" value="@Model.ID" />

    <label asp-for="Name" class="control-label">Name</label>
    <input type="text" name="Name" class="form-control" value="@Model.Name" />

    <label asp-for="Description" class="control-label">Description</label>
    <input type="number" step="0.01" name="Description" class="form-control" value="@Model.Description" />

    <label asp-for="Unit_of_Measurement" class="control-label">Unit of Measurement</label>
    <input type="number" step="0.01" name="Unit_of_Measurement" class="form-control" value="@Model.Unit_of_Measurement" />

    <label asp-for="Quantity_in_stock" class="control-label">Quantity in Stock</label>
    <input type="number" step="0.01" name="Quantity_in_stock" class="form-control" value="@Model.Quantity_in_stock" />

    <input type="submit" value="Update Ingredient" class="btn btn-primary" />
}

Cupcake-Project/Views/Ingredient/ViewIngredient.cshtml
@model Ingredient

<h3>@Model.Name Information</h3>

<table class="table">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Description</th>
        <th>Quantity in Stock</th>
        <th>Unit of Measurement</th>
    </tr>
    <tr>
        <td>@Model.ID</td>
        <td>@Model.Name</td>
        <td>@Model.Description</td>
        <td>@Model.Quantity_in_stock</td>
        <td>@Model.Unit_of_Measurement</td>
    </tr>
</table>

<div style="display: block">
    <a href="/Ingredient/UpdateIngredient/@Model.ID">Update this Ingredient</a>
</div>

<div style="display: block">

    @using (Html.BeginForm("DeleteIngredient", "Ingredient", "Post"))
    {
        <input type="hidden" asp-for="ID" value="@Model.ID" />
        <input type="submit" onclick="return confirm('Are you sure?')" value="Delete this Ingredient" />
    }
</div>

Cupcake-Project/Views/Product/Index.cshtml
@model IEnumerable<Product>

<h2>Products</h2>

  <div style="display: block">
    <a href="/Product/InsertProduct/">Create a New Product</a>
 </div>


<table class="table">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
        <th>Quantity In Stock</th>
    </tr>

    @foreach (var product in @Model)
    {
        <tr>
            <td><a href=/Product/ViewProduct/@product.ID>@product.ID</a></td>
            <td>@product.Name</td>
            <td>@product.Description</td>
            <td>@product.Price</td>
            <td>@product.Quantity_In_Stock</td>
        </tr>
    }

</table>

Cupcake-Project/Views/Product/InsertProduct.cshtml
@model Product

<h2 class="text-center">Create a New Product</h2>

@using (Html.BeginForm("InsertProductToDatabase", "Product", "Post"))
{
    <input asp-for="ID" type="hidden" value="" />

    <label asp-for="Name" class="control-label">Name</label>
    <input type="text" name="Name" class="form-control" value=""/>

    <label asp-for="Description" class="control-label">Description</label>
    <input type="text" name="Description" class="form-control" value="" />

    <label asp-for="Price" class="control-label">Price</label>
    <input type="number" name="Price" class="form-control" />

    <label asp-for="Quantity_In_Stock" class="control-label">Quantity In Stock</label>
    <input type="number" name="Quantity_In_Stock" class="form-control" />


    <button class="button" role="button" type="submit">Add Product</button>
    <a class="button" href="/Product/Index">Back</a>
}

Cupcake-Project/Views/Product/Product_Index.cshtml
@model IEnumerable<Product>

<h2>Products</h2>
<table class="table">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
        <th>Quantity In Stock</th>
    </tr>

    @foreach (var product in @Model)
    {
        <tr>
            <td>@product.ID</td>
            <td>@product.Name</td>
            <td>@product.Description</td>
            <td>@product.Price</td>
            <td>@product.Quantity_In_Stock</td>
        </tr>
    }

</table>

Cupcake-Project/Views/Product/UpdateProduct.cshtml
@model Product

<h2>Update @Model.Name</h2>

@using (Html.BeginForm("UpdateProductToDatabase", "Product", "Post"))
{
    <input asp-for="ID" type="hidden" value="@Model.ID" />

    <label asp-for="Name" class="control-label">Name</label>
    <input type="text" name="Name" class="form-control" value="@Model.Name" />

    <label asp-for="Description" class="control-label">Description</label>
    <input type="text" name="Description" class="form-control" value="@Model.Description" />

    <label asp-for="Price" class="control-label">Price</label>
    <input type="number" step="0.01" name="Price" class="form-control" value="@Model.Price" />

    <label asp-for="Quantity_In_Stock" class="control-label">Quantity In Stock</label>
    <input type="number" name="Quantity_In_Stock" class="form-control" value="@Model.Quantity_In_Stock" />

    <input type="submit" value="Update Product" class="btn btn-primary" />
}

Cupcake-Project/Views/Product/ViewProduct.cshtml
@model Product

<h3>@Model.Name Information</h3>

<table class="table">
    <tr>
        <th>Product ID</th>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
        <th>Quantity In Stock</th>
       
    </tr>
    <tr>
        <td>@Model.ID</td>
        <td>@Model.Name</td>
        <td>@Model.Description</td>
        <td>@Model.Price</td>
        <td>@Model.Quantity_In_Stock</td>
  
    </tr>
</table>

<div class ="buttons">
   
<div style="display: inline">
    <a href="/Product/UpdateProduct/@Model.ID">Update this Product</a>
</div>

<div style="display: inline">

    @using (Html.BeginForm("DeleteProduct", "Product", "Post"))
    {
        <input type="hidden" asp-for="ID" value="@Model.ID" />
        <input type="submit" onclick="return confirm('Are you sure?')" value="Delete this product" />
    }
    </div>
</div>

Cupcake-Project/Views/Recipe/Index.cshtml
@model IEnumerable<Recipe>

<h2>Recipes</h2>

   <div style="display: block">
     <a href="/Recipe/InsertRecipe/">Add Recipe</a>
 </div>

<table class="table">
    <tr>
        <th>ID</th>
        <th>Product ID</th>
        <th>Ingredient ID</th>
        <th>Quantity Required</th>
    </tr>

    @foreach (var recipe in @Model)
    {
        <tr>
            <td><a href=/Recipe/ViewRecipe/@recipe.ID>@recipe.ID</a></td>
            <td>@recipe.Product_ID</td>
            <td>@recipe.Ingredient_ID</td>
            <td>@recipe.Quantity_Required</td>
        </tr>
    }

</table>

Cupcake-Project/Views/Recipe/InsertRecipe.cshtml
@model Recipe

<h2>Create a New Recipe</h2>

@using (Html.BeginForm("InsertRecipeToDatabase", "Recipe", "Post"))
{
    <input asp-for="ID" type="hidden" value="" />

    <label asp-for="Product_ID" class="control-label">Product ID</label>
    <input type="number" step="1" name="Product_ID" class="form-control" />

    <label asp-for="Ingredient_ID" class="control-label">Ingredient ID</label>
    <input type="number" step="1" name="Ingredient_ID" class="form-control" />

    <label asp-for="Quantity_Required" class="control-label">Quantity Required</label>
    <input type="number" step="0.01" name="Quantity_Required" class="form-control" />

    <input type="submit" value="Create Recipe" class="btn btn-primary" />
}

Cupcake-Project/Views/Recipe/UpdateRecipe.cshtml
@model Recipe

<h2>Update Recipe</h2>

@using (Html.BeginForm("UpdateRecipeToDatabase", "Recipe", "Post"))
{
    <input asp-for="ID" type="hidden" value="@Model.ID" />

    <label asp-for="Product_ID" class="control-label">Product ID</label>
    <input type="number" step="1" name="Product_ID" class="form-control" value="@Model.Product_ID" />

    <label asp-for="Ingredient_ID" class="control-label">Ingredient ID</label>
    <input type="number" step="1" name="Ingredient_ID" class="form-control" value="@Model.Ingredient_ID" />

    <label asp-for="Quantity_Required" class="control-label">Quantity Required</label>
    <input type="number" step=".01" name="Quantity_Required" class="form-control" value="@Model.Quantity_Required" />

    <input type="submit" value="Update Recipe" class="btn btn-primary" />
}

Cupcake-Project/Views/Recipe/ViewRecipe.cshtml
@model Recipe

<h3>Recipe Information</h3>

<table class="table">
    <tr>
        <th>ID</th>
        <th>Product ID</th>
        <th>Ingredient ID</th>
        <th>Quantity Required</th>
    </tr>
    <tr>
        <td>@Model.ID</td>
        <td>@Model.Product_ID</td>
        <td>@Model.Ingredient_ID</td>
        <td>@Model.Quantity_Required</td>
    </tr>
</table>

<div style="display: block">
    <a href="/Recipe/UpdateRecipe/@Model.ID">Update Recipe</a>
</div>

<div style="display: block">

    @using (Html.BeginForm("DeleteRecipe", "Recipe", "Post"))
    {
        <input type="hidden" asp-for="ID" value="@Model.ID" />
        <input type="submit" onclick="return confirm('Are you sure?')" value="Delete this recipe" />
    }
</div>

Cupcake-Project/Views/Recipes/Recipes_Index.cshtml
@model IEnumerable<Recipe>

<h2>Recipes</h2>
<table class="table">
    <tr>
        <th>ID</th>
        <th>Product ID</th>
        <th>Ingredient Id</th>
        <th>Product Required</th>
    </tr>

    @foreach (var recipe in @Model)
    {
        <tr>
            <td>@recipe.ID</td>
            <td>@recipe.Product_ID</td>
            <td>@recipe.Ingredient_ID</td>
            <td>@recipe.Quantity_Required</td>
        </tr>
    }

</table>

Cupcake-Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cupcake_Project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Cupcake_Project.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Cupcake_Project</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ingredient" asp-action="Index">Ingredients</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Recipe" asp-action="Index">Recipes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Cupcake_Project - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>